### PR TITLE
DragonsArena

### PR DESCRIPTION
**Pull request by butavpaul**
Name of the project
Dragons Arena

Description of the project
Dragons Arena is am NFT project launched at the beginning of this year and it's main utility is developing a Play To Earn game. The game is called Gods Of Fire (https://twitter.com/godsoffire_io).

Our holders will have as benefits:

- early access to the game and free in-game characters
- token airdrop (To be launched on Krogan Launchpad https://kroganlaunchpad.com/godsoffire)
Besides the main utilities from above, for our Dragons Arena holders at first we've created the first Augmented Reality app on Elrond Network with utility available on iOS & Android: Android: https://play.google.com/store/apps/details?id=com.DragonsArenaAR iOS: https://apps.apple.com/us/app/dragons-ar-connect/id1621731320 With AR Connect (The name of the app) holders can transpose 1:1 their Dragons Arena NFTS into the real world and participate in daily raffles (At every 4 hours, a box containing a prize (LKMEX, EGLD, NFT), close to a random dragon is airdroped. The holders had 24h time to claim the reward). You can see all the rewards distributed here: https://dragonsarena.io/ar Also with the utility of the app, we've connected with lots of NFT projects who joined our AR Connect program (Partners offered us NFTS to be claimed in our app).

Lately, this weeks we've developed a new app for mobiles where our holders can stake their NFTS. The app is already available for iOS & Android and our holders already staked more than 700+ NFTS (From 2,000). Android: https://play.google.com/store/apps/details?id=com.DragonsArenaSpace iOS: https://apps.apple.com/us/app/dragons-arena-space/id6444228197 Our staking method is different from classic staking, because, our holders need to stake daily their NFTS and in this way, they can keep their NFTS into their wallet (No need to transfer into a smart contract. In this way, our holders can still transpose their NFTS into the real world (Augmented reality - The fist application)).

We've developed the apps for our holders, so we can engage and keep our community strong until the game will be released (Next year). In this way we've created a strong and united community.

Staking will be available also in AR Connect (First application). We've chosen this way to create 2 different apps, because some devices doesn't support AR Core. Resume:

first app (AR Connect): Augmented reality app with daily raffles & staking (For devices which support AR Core)
second app (Dragons Arena Space): For devices which doesn't support AR Core
Purpose
We've launched our staking app publicly 2 days ago and more then 100+ holders staked more then 700+ NFTS. In exchange, as rewards, we give LKMEX. We have a new staking pool every week (We've created this way, so we can add a special pool (Different traits) to give more to holders (different every week)) and the first LKMEX distribution will take place this Monday. Having the possibility to continue offering LKMEX to our holders will help us keep the community close and to develop the app more and more. We tend to create a mobile metaspace, where users can transpose/stake/read latest news from egld.community (Already implemented)/gamify(Increase in levels) and more. Currently connection on the app it's possible with a wallet address and a password:

the password is generated on our website https://dragonsarena.io/account We've chosen this way as a door to our app, but in future, we tend to implement Maiar login (The app is created in Unreal Engine and currently there're no plugins available, but we'll develop it for our apps). Having the opportunity to use LKMEX transfers, will increase the project's value and our holders are rewarded at the same time they're waiting for the game to be released. The smart contract we tend to use for transfers is simple, with a single endpoint, which transfers a specific amount of tokens to a specific wallet.
https://dragonsarena.io/ https://godsoffire.io/

Address of Smart Contract
erd1qqqqqqqqqqqqqpgqn64cnrs7mvqwh7s3ntaxceyzt7jyaqwwsteskf8ksp https://explorer.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqn64cnrs7mvqwh7s3ntaxceyzt7jyaqwwsteskf8ksp

Smart Contract Code
https://github.com/butavpaul/SCTransferToken

Description for every Smart Contract functionality
https://github.com/butavpaul/SCTransferToken/blob/main/src/utils/send.rs

Endpoint: esdtMultiTransfer Transfer LKMEX token to specific wallets with specific amount.

Number of users
100-300

Average LKMEX used during the previous month
8,000,000 LKMEX - when we had only AR Connect for rewards. This week, since we've opened our staking app, we've distributed 7,000,000 LKMEX (This means we'll distribute around 28-30M LKMEX / month)

### CODE REVIEW

**Comment by butavpaul** [comment]
Name of the project
Dragons Arena

Description of the project
Dragons Arena is am NFT project launched at the beginning of this year and it's main utility is developing a Play To Earn game. The game is called Gods Of Fire (https://twitter.com/godsoffire_io).

Our holders will have as benefits:

- early access to the game and free in-game characters
- token airdrop (To be launched on Krogan Launchpad https://kroganlaunchpad.com/godsoffire)
Besides the main utilities from above, for our Dragons Arena holders at first we've created the first Augmented Reality app on Elrond Network with utility available on iOS & Android: Android: https://play.google.com/store/apps/details?id=com.DragonsArenaAR iOS: https://apps.apple.com/us/app/dragons-ar-connect/id1621731320 With AR Connect (The name of the app) holders can transpose 1:1 their Dragons Arena NFTS into the real world and participate in daily raffles (At every 4 hours, a box containing a prize (LKMEX, EGLD, NFT), close to a random dragon is airdroped. The holders had 24h time to claim the reward). You can see all the rewards distributed here: https://dragonsarena.io/ar Also with the utility of the app, we've connected with lots of NFT projects who joined our AR Connect program (Partners offered us NFTS to be claimed in our app).

Lately, this weeks we've developed a new app for mobiles where our holders can stake their NFTS. The app is already available for iOS & Android and our holders already staked more than 700+ NFTS (From 2,000). Android: https://play.google.com/store/apps/details?id=com.DragonsArenaSpace iOS: https://apps.apple.com/us/app/dragons-arena-space/id6444228197 Our staking method is different from classic staking, because, our holders need to stake daily their NFTS and in this way, they can keep their NFTS into their wallet (No need to transfer into a smart contract. In this way, our holders can still transpose their NFTS into the real world (Augmented reality - The fist application)).

We've developed the apps for our holders, so we can engage and keep our community strong until the game will be released (Next year). In this way we've created a strong and united community.

Staking will be available also in AR Connect (First application). We've chosen this way to create 2 different apps, because some devices doesn't support AR Core. Resume:

first app (AR Connect): Augmented reality app with daily raffles & staking (For devices which support AR Core)
second app (Dragons Arena Space): For devices which doesn't support AR Core
Purpose
We've launched our staking app publicly 2 days ago and more then 100+ holders staked more then 700+ NFTS. In exchange, as rewards, we give LKMEX. We have a new staking pool every week (We've created this way, so we can add a special pool (Different traits) to give more to holders (different every week)) and the first LKMEX distribution will take place this Monday. Having the possibility to continue offering LKMEX to our holders will help us keep the community close and to develop the app more and more. We tend to create a mobile metaspace, where users can transpose/stake/read latest news from egld.community (Already implemented)/gamify(Increase in levels) and more. Currently connection on the app it's possible with a wallet address and a password:

the password is generated on our website https://dragonsarena.io/account We've chosen this way as a door to our app, but in future, we tend to implement Maiar login (The app is created in Unreal Engine and currently there're no plugins available, but we'll develop it for our apps). Having the opportunity to use LKMEX transfers, will increase the project's value and our holders are rewarded at the same time they're waiting for the game to be released. The smart contract we tend to use for transfers is simple, with a single endpoint, which transfers a specific amount of tokens to a specific wallet.
https://dragonsarena.io/ https://godsoffire.io/

Address of Smart Contract
erd1qqqqqqqqqqqqqpgqn64cnrs7mvqwh7s3ntaxceyzt7jyaqwwsteskf8ksp https://explorer.elrond.com/accounts/erd1qqqqqqqqqqqqqpgqn64cnrs7mvqwh7s3ntaxceyzt7jyaqwwsteskf8ksp

Smart Contract Code
https://github.com/butavpaul/SCTransferToken

Description for every Smart Contract functionality
https://github.com/butavpaul/SCTransferToken/blob/main/src/utils/send.rs

Endpoint: esdtMultiTransfer Transfer LKMEX token to specific wallets with specific amount.

Number of users
100-300

Average LKMEX used during the previous month
8,000,000 LKMEX

**Comment by sasurobert** [comment]
We are reviewing the contract.

**Review by sasurobert — CHANGES_REQUESTED** [review]
Hello DragonsArena,

After a thorough analysis of your Pull Request, we have concluded that we are unable to provide a ‘whitelisted’ status. The reasoning behind this decision is the fact that your project uses an endpoint that sends arbitrary amounts of XMEX to a list of wallets and should it ever happen that the project’s keys are compromised or some illegitimate XMEX transfers are made, it would be difficult to detect and take action.
Our advice would be to create a proper NFT Staking Smart Contract where only the owner is allowed to deposit XMEX. Users can claim their rewards if they stake the NFT or by sending the NFT to the contract (thus proving that they own the NFT).

Have a productive day!

**Comment by sasurobert** [comment]
Hello DragonsArena,

After a thorough analysis of your Pull Request, we have concluded that we are unable to provide a ‘whitelisted’ status. The reasoning behind this decision is the fact that your project uses an endpoint that sends arbitrary amounts of XMEX to a list of wallets and should it ever happen that the project’s keys are compromised or some illegitimate XMEX transfers are made, it would be difficult to detect and take action.
Our advice would be to create a proper NFT Staking Smart Contract where only the owner is allowed to deposit XMEX. Users can claim their rewards if they stake the NFT or by sending the NFT to the contract (thus proving that they own the NFT).

Have a productive day!

**Pull request closed without merging**
